### ISSUE TITLE
Having problems testing it out

### ISSUE THREAD

**Issue by badjoerichards** [iomintz/acnh-api#4]
Hi there,

Love your work, but I had some problems trying out your api, getting errors:
{"http_status": 500, "http_status_name": "Internal Server Error", "http_status_description": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."}

questions:

1. Is it working? Cos I'm getting errors testing your API you hosted.
2. How can I host my own API? 
- 2a. New to this, I suppose I would need a hacked/unpatched Switch device yes? 
- 2b. Is acnh-api supposed to run on the hacked Switch or a separate computer/webserver?

Thanks for your time!

joe

**Comment by iomintz** [comment]
Oh, looks like I just forgot an import. Don't know how that slipped through.

**Comment by iomintz** [comment]
As for your other question. Yes you need a hacked switch and a copy of Animal Crossing from the eShop to extract various keys from. No, it runs on a separate computer. If you have an unpatched switch (use [SSNC](https://damota.me/ssnc/checker/) to check) then I can help you through the process outlined in the README.

Which endpoint were you getting errors on? Was it just /host-session/:dodo-code? That one should be fixed now, but let me know if it's not.

**Comment by badjoerichards** [comment]
I was getting errors on just the /host-session/:dodo-code endpoint, and yes working now!

Looks like my switch won't work for now, will try to get my hands on an unpatched one, thanks for offering to help walk me through :) 💯 

Is there a way we can connect? I'd like to support your work and also get your help to run an API server too

joe
